name: web_layout_one
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  data_table_2: ^2.3.12
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  animations: ^2.0.2
  responsive_framework: ^0.2.0

flutter:
  uses-material-design: true
assets:
    - assets/mugs_side_bw_w1080.jpg